# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec — PC Doctor standalone EXE."""

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'psutil',
        'psutil._pswindows',
        'tkinter',
        'tkinter.ttk',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'sqlite3',
        'ctypes',
        'ctypes.wintypes',
        'winreg',
        'core',
        'core.actions',
        'core.scheduler',
        'core.score',
        'core.storage',
        'core.report',
        'core.inventory',
        'core.process_baseline',
        'core.checks',
        'core.checks.base',
        'core.checks.cpu',
        'core.checks.memory',
        'core.checks.disk',
        'core.checks.hardware',
        'core.checks.graphics',
        'core.checks.windows',
        'core.checks.eventlog',
        'core.checks.network',
        'core.checks.battery',
        'core.checks.temperature',
        'core.checks.process',
        'core.checks.uptime',
        'core.checks.os_info',
        'ui',
        'ui.app',
        'ui.theme',
        'ui.views.dashboard',
        'ui.views.maintenance',
        'ui.views.history',
        'ui.views.settings',
        'ui.widgets.quick_tools',
        'ui.widgets.vital_card',
        'ui.widgets.prescription',
        'ui.widgets.score_gauge',
        'ui.widgets.rounded',
        'utils.platform',
        'utils.notify',
        'utils.format',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['matplotlib', 'numpy', 'PIL', 'cv2', 'scipy'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PC닥터',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,        # 콘솔 창 숨김 (GUI 앱)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=False,
)
